# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='title',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
